### ISSUE TITLE
Emojis are broken

### ISSUE THREAD

**Issue by MarGar12** [MiRinChan/OhMyFontOnAndroid15#1]
Using an emoji ttf also doesn't work
![Screenshot_20241201-202242.png](https://github.com/user-attachments/assets/d0eccd8b-aacf-4fd4-bc19-1c5e62bd63b4)

I'm using this module if you wanna test it out: https://github.com/nongthaihoang/custom_font_installer

**Comment by MiRinChan** [comment]
it may font problem, only monochrome variety display

despite this font may have colorful variety but you may do some about config

this is not a plugin problem

**Comment by MarGar12** [comment]
well without using this script, the emojis worked, but the fonts don't

oh and the default emojis don't work either
